name: Congratulate First Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  congratulate:
    runs-on: ubuntu-latest
    steps:
      - name: Greet First-Time Contributor
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;

            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });

            const userPRs = pulls.filter(pr => pr.user.login === prAuthor);

            if (userPRs.length === 1) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `🎉 Congratulations @${prAuthor} on opening your first pull request!`
              });
            }
