name: Comment on Closed Issue

on:
  issues:
    types:
      - closed
jobs:
  label_issues: # juuu
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Comment on closed issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number}}
          body: | # The body of the comment is a message thanking the user for opening the issue.
           Issue on valmis!
