name: Comment on Closed Issue

on:
  issues:
    types: [closed]

jobs:
  comment:
    if: github.event.issue.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on closed issue
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "The issue is now resolved."
            });
